/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package dk.preuss.utils

import spock.lang.Specification

class StringJoinerTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def stringJoiner = new StringJoiner()

        when:
        def result = stringJoiner.length()

        then:
        result == 0
    }
}
